# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: xcode-lambda # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10

  # you can overwrite defaults here
  #  stage: dev
  #  region: us-east-1

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sqs:*'
      Resource: 'arn:aws:sqs:${file(./env-local.yml):REGION}:${file(./env-local.yml):ACCOUNT}:*'
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
        - 's3:GetObject'
      Resource: 'arn:aws:s3:::scout-streaming-2018/*'
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/*'

functions:
  xcode:
    handler: handler.xcode
    environment:
      OPUS_CAF_ARGS: -codec:a libopus -ar 48000 -b:a 24k -f caf
      OPUS_MKV_ARGS: -codec:a libopus -ar 48000 -b:a 24k
      POLLY_S3_BUCKET: ${file(./env-local.yml):POLLY_S3_BUCKET}
    timeout: 420
    reservedConcurrency: 1
    events:
      - sqs:
          batchSize: 1
          enabled: true
          arn: 'arn:aws:sqs:us-east-1:${file(./env-local.yml):ACCOUNT}:xcode-queue'

# you can add CloudFormation resource templates here
resources:
  Resources:
    xcode:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: xcode-queue
        VisibilityTimeout: 420
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
            - xcodeDeadLetterQueue
            - Arn
          maxReceiveCount: 10

    xcodeDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: xcode-dead-letter-queue
        MessageRetentionPeriod: 1209600

